name: Awake Action
on:
  schedule:
    # every 25 minutes, the steps below are triggered
    - cron: "25 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: main-awake
        uses: devpolo/awake-action@v1
        with:
          url: "https://jones-nodebucket.herokuapp.com/"
